trigger:
- main

parameters:
- name: package_version
  displayName: Package Version
  type: string
  default: 1.1

variables:
  PACKAGE_VERSION: ${{ parameters.package_version }}.$(Build.BuildId)

stages:
- stage: Build
  displayName: Build Package
  jobs:
      - job:
        displayName: ubuntu-latest
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            # Python36:
            #   python.version: '3.6'
            #   env_file: 'environment.yml'
            Python38:
              python.version: '3.8'              
              env_file: 'environment_py38.yml'
              
        steps:
        - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH

        # Install mamba to manage dependencies faster
        - bash: |
            conda config --set allow_conda_downgrades true
            conda install conda=4.12.0 -y
            conda install --yes mamba -c conda-forge
          displayName: Install Mamba package manager

        - bash: |
            # workaround based on recent failures
            rm /usr/share/miniconda/pkgs/cache/*.json    
            mamba env create --file $(env_file)
          displayName: Create mamba environment
      
        - bash: |
            python setup.py bdist_wheel
          displayName: Build wheel

        - script: 'pip install twine keyring artifacts-keyring'
          displayName: Install publishing prerequisites
  
        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: 'Warn-on-Forecast/wofs-post'
          displayName: Authenticate Twine

        - script: |
            python -m twine upload -r wofs-post --config-file $(PYPIRC_PATH) --skip-existing dist/*.whl
          displayName: Publish Package

        - task: GithubRelease@1 
          displayName: 'Create GitHub Release'
          inputs:
            gitHubConnection: WarnOnForecast-Github
            repositoryName: WarnOnForecast/ml_workflow
            isPreRelease: false
            tagSource: userSpecifiedTag
            assets: dist/*.whl
            tag: $(PACKAGE_VERSION)-py$(python.version)
